[package]
name = "rust_verifier"
version = "1.0.0"
authors = ["jack the dev <joao@hackachain.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0", features = ["unstable"] }
near-bigint = { path = "../../near_bigint" }

[dev-dependencies]
rstest = "0.14.0"