[package]
name = "fungible_token"
version = "1.0.0"
authors = ["hack-a-du"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "4.1.1"
near-sdk = "4.1.1"
